### ISSUE TITLE
AesGcmDecryptor.Dispose() throws NotImplementedException

### ISSUE THREAD

**Issue by justrand** [Innofactor/Innofactor.SuomiFiIdentificationClient#11]
I ran into an issue when running the library that `AesGcmDecryptorDispose()` is called and it has no implementation so it causes the identification to crash. This might be a net7.0 issue. Perhaps the earlier frameworks don't call it.
 
I made a fork from the release and tested by adding an empty implementation to the function:
```
public void Dispose() { }
```
This works and suomi.fi identication works with this change but it would be helpful to have the "fix" in the official release. As far as I can tell, the Dispose function doesn't have any cleanup to do as the class members are initialized in the constructor and would be freed when the object is no longer needed. And other objects taking memory are used in the TransformFinalBlock() function as local variables so they should be freed when the function exits. So, therefore an empty implementation of Dispose() should be enough?

**Comment by AlexEngblom** [comment]
I'll try to look into this next week with better time, but at the first glance it looks like your conclusion seems correct.

**Comment by AlexEngblom** [comment]
Fixed and published in 3.0.6
