### ISSUE TITLE
No implicit reference conversion from RshShaCrypto to ICertificateStore

### ISSUE THREAD

**Issue by tungsnguyen** [Innofactor/Innofactor.SuomiFiIdentificationClient#5]
When I add this registration:
services.AddScoped<ICertificateStore, RsaShaCrypto>();

the compiler complains and shows error:

Error CS0311 The type 'Innofactor.SuomiFiIdentificationClient.Support.RsaShaCrypto' cannot be used as type parameter 'TImplementation' in the generic type or method 'ServiceCollectionServiceExtensions.AddScoped<TService, TImplementation>(IServiceCollection)'. There is no implicit reference conversion from 'Innofactor.SuomiFiIdentificationClient.Support.RsaShaCrypto' to 'Innofactor.SuomiFiIdentificationClient.Support.ICertificateStore'

**Comment by jannef** [comment]
RsaShaCrypto does not implement ICertificate store. Instead, RsaShaCrypto depends on ICertificate store. DI configuration could look like this:

```cs
/*
   Inject SamlConfig to DI in your preferred way here.  Both CertificateStore and RsaShaCrypto require it.
*/
// the package offers CertificateStore, which is an implementation for Windows local certificate store
services.AddScoped<ICertificateStore, CertificateStoreImplementation>();
services.AddScoped<RsaShaCrypto>();
```
